import Head from 'next/head';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai';
import Image from 'next/image';
import deved from '../public/dev-ed-wave.png';
import design from '../public/design.png';
import code from '../public/code.png';
import consulting from '../public/consulting.png';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title> Arnold Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 dark:text-white" >
        <section className="min-h-screen">
          <nav className="p-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons pr-10 pl-0" >ArnoldR</h1>
            <ul className="flex items-center ">
              <li className=""><BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl"/></li>
              <li className="pr-2 pl-2"><a href="#">work</a></li>
              <li className="pr-2"><a href="#">skills</a></li>
              <li className="pr-2"><a href="#">contact</a></li>
             
            </ul>
          </nav>
          <div className="text-center p-10 ">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">Arnold Ramodike</h2>
            <h3 className="text-2xl pt-2 md:text-3xl"> Developer and Data Analyst</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white"> 
              I am an aspirering Junior Programmer who has a knack for numbers and love big data. 
              In my current role, I am developing and maintaining web applications in React and .net. 
              Production support for an international enterprise in the banking sector. Handling Debugging and troubleshooting. 
              Develop strategies to ensure compliance with new standards. Analyzing internal and external data and developing insights and
              reports that help the management take business decisions.
              I collaborate well with the technical and business stuff in the design, and development of applications and reports.
              </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-white">
            <AiFillLinkedin/>
            <AiFillTwitterCircle href="https://github.com/ArnoldRamodike"/>
            <AiFillYoutube/>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96 ">
          <Image src={deved} layout="fill" objectFit="cover" alt=""/>
          </div>
        </section> 
        <section> 
          <div>
            <h3 className="text-3xl py-1 text-center">Work Experience</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white"> Since the begginignof time my jeorneu has been a chartedred accont
            <span className="text-teal-500"> agencies </span>
            consulted fro <span className="text-teal-500">stargazing </span> 
              and collaborated with talented people to create digital functionalities for both business and consumer use
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white"> Since the begginignof time my jeorneu has been a chartedred accont</p>
          </div>
          <div className="lg:flex gap-20 ">
          
            <div className="text-center  rounded-xl my-10">
              <Image src={design} width={100} height={100} alt="" className="mx-auto"/>       
              <h3 className="text-lg font-medium pt-8 pb-2 ">Previous Companies</h3>
              <p className="text-md py-2 leading-8 text-gray-800"></p>
              <h4></h4>
              <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <p className="text-teal-500 py-1">Unitec Solution<span className="text-black pl-5 dark:text-white">2020-2021</span></p>
              <h4 className="text-gray-800 py-2 dark:text-white">Trainee</h4>
              <p className="text-gray-800 py-2 dark:text-white">Web Development using Laravel/PHP and HTML/CSS and Java Script</p>
              </div>
              
              <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <p className="text-teal-500 py-1">Singular Systems<span className="text-black pl-5 dark:text-white">2021-2022</span></p>
              <h4 className="text-gray-800 py-2 dark:text-white">Internship</h4>
              <p className="text-gray-800 py-2 dark:text-white">Maintenance of Internal and External Systems Development using .Net framework.</p>
              </div>
              <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <p className="text-teal-500 py-1">Singular Systems <span className="text-black pl-5 dark:text-white">2022-2023</span></p>
              <h4 className="text-gray-800 py-2 dark:text-white">Junior Programmer</h4>
              <p className="text-gray-800 py-2 dark:text-white">Developing new functions into test Automation Framework in .NET and React.
              Microsoft Dynamics 365 Customizations in C# and Java Script. Production support for international clients.</p>
              </div>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 text-center">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white md:text-xl max-w-lg mx-auto"> Below are some of the 
            <span className="text-teal-500"> Skillsets </span>
           That i posses <span className="text-teal-500">stargazing </span> 
              and collaborated with talented people to create digital functionalities for both business and consumer use
            </p>
          </div>
          <div className="lg:flex gap-20">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 ">
              <Image src={design} width={100} height={100} alt="" className="mx-auto"/>             
              <h3 className="text-lg font-medium pt-8 pb-2">Front-End Development</h3>
              <p className="text-md py-2 leading-8 text-gray-800">  Designs tools I use:</p>
              <h4></h4>
              <p className="text-gray-800 dark:text-white py-1">HTML5/CSS3</p>
              <p className="text-gray-800 dark:text-white py-1">Javascript</p>
              <p className="text-gray-800 dark:text-white py-1">React JS</p>
              <p className="text-gray-800 dark:text-white py-1">Saas</p>
              <p className="text-gray-800 dark:text-white py-1">Typescript</p>
              <p className="text-gray-800 dark:text-white py-1">.NET</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={code} width={100} height={100} alt="" className="mx-auto"/>             
              <h3 className="text-lg font-medium pt-8 pb-2">Back-End Development</h3>
              <p className="text-lg py-2 leading-8 text-purple-800">The toold I use:</p>
              <h4 className="text-purple-700 text-lg py-2"> </h4>
              <p className="text-gray-800 dark:text-white py-1">C# & C++</p>
              <p className="text-gray-800 dark:text-white py-1">Laravel</p>
              <p className="text-gray-800 dark:text-white py-1">Node Js</p>
              <p className="text-gray-800 dark:text-white py-1">Java</p>
              <p className="text-gray-800 dark:text-white py-1">Visual Basic</p>
              <p className="text-gray-800 dark:text-white py-1">php</p>
              <p className="text-gray-800 dark:text-white py-1">Source Control</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10">
              <Image src={consulting} width={100} height={100} alt="" className="mx-auto"/>             
              <h3 className="text-lg font-medium pt-8 pb-2">Data Analysis</h3>
              <p className="text-md py-2 leading-8 text-gray-800">For Analysis and Designs: </p>
              <h4> </h4>
              <p className="text-gray-800 dark:text-white py-1">Power BI</p>
              <p className="text-gray-800 dark:text-white py-1">SQL & MySQL</p>
              <p className="text-gray-800 dark:text-white py-1">Excell</p>
              <p className="text-gray-800 dark:text-white py-1">Mongo Db</p>
              <p className="text-gray-800 dark:text-white py-1">Python</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 text-center">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white"> These are some of the  
            <span className="text-teal-500"> Projects </span>
            That i have worked on. The code for all these projects is in my <span className="text-teal-500">Github </span> 
             repository.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
            <h3 className="text-lg font-medium pt-8 pb-2 text-center text-teal-500">The Admin Dashboard</h3>
              <a href="https://riccoadmin.netlify.app">
              <Image src={web1} className="rounded-lg object-cover" alt="" width={'100%'} height={'100%'} layout="responsive"/>
              </a>
            </div>
            <div className="basis-1/3 flex-1">
            <h3 className="text-lg font-medium pt-8 pb-2 text-center text-teal-500">E-Commerce app</h3>
              <a href="https://riccoadmin.netlify.app">
              <Image src={web2} className="rounded-lg object-cover" alt="" width={'100%'} height={'100%'} layout="responsive"/>
              </a>
            </div>
            <div className="basis-1/3 flex-1">
            <h3 className="text-lg font-medium pt-8 pb-2 text-center text-teal-500">Music App with shazam API</h3>
              <a href="https://riccoadmin.netlify.app">
              <Image src={web3} className="rounded-lg object-cover" alt="" width={'100%'} height={'100%'} layout="responsive"/>
              </a>
            </div>
            <div className="basis-1/3 flex-1">
            <h3 className="text-lg font-medium pt-8 pb-2 text-center text-teal-500">Full-Stack Blog Application</h3>
              <a href="https://riccoadmin.netlify.app">
              <Image src={web5} className="rounded-lg object-cover" alt="" width={'100%'} height={'100%'} layout="responsive"/>
              </a>
            </div>
            <div className="basis-1/3 flex-1">
            <h3 className="text-lg font-medium pt-8 pb-2 text-center text-teal-500">Social Media Platform</h3>
              <a href="https://riccoadmin.netlify.app">
              <Image src={web4} className="rounded-lg object-cover" alt="" width={'100%'} height={'100%'} layout="responsive"/>
              </a>
            </div>
            <div className="basis-1/3 flex-1">
            <h3 className="text-lg font-medium pt-8 pb-2 text-center text-teal-500">Dashboard Interface</h3>
              <a href="https://riccoadmin.netlify.app">
              <Image src={web6} className="rounded-lg object-cover" alt="" width={'100%'} height={'100%'} layout="responsive"/>
              </a>
            </div>
          </div>
        </section>
        <footer>
          <p className="text-gray-800 text-center text-lg shadow-lg dark:text-white"> Designed by <span className="text-teal-500">Arnold Ramodike</span> with ❤️ </p>
        </footer>
      </main>
      </div>
  );
}
